builds:
  - id: ping-pong-server
    main: server/server.go
    binary: ping-pong-server
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7

dockers:
  - id: ping-pong-server
    goos: linux
    goarch: amd64
    ids:
      - ping-pong-server
    image_templates:
      - "ghcr.io/huseyinbabal/ping-pong-server:{{.Tag}}"
    build_flag_templates:
      - "--label=org.opencontainers.image.source=https://github.com/huseyinbabal/grpc-ping-pong"
    skip_push: false
    dockerfile: Dockerfile.server
