builds:
  - id: pingpongserver
    main: server/server.go
    binary: pingpongserver
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

dockers:
  - id: pingpongserver
    goos: linux
    goarch: amd64
    ids:
      - pingpongserver
    image_templates:
      - "ghcr.io/huseyinbabal/ping-pong-server:{{.Tag}}"
    build_flag_templates:
      - "--label=org.opencontainers.image.source=https://github.com/huseyinbabal/grpc-ping-pong"
    skip_push: false
    dockerfile: Dockerfile.server
