builds:
  - id: ping-pong-server
    main: server/server.go
    binary: ping-pong-server
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - id: ping-pong-server
    goos: linux
    goarch: amd64
    ids:
      - ping-pong-server
    image_templates:
      - "ghcr.io/huseyinbabal/ping-pong-server:{{.Commit}}"
    build_flag_templates:
      - "--build-arg=module=ping-pong-server"
      - "--label=org.opencontainers.image.source=https://github.com/huseyinbabal/grpc-ping-pong"
    skip_push: false
    dockerfile: Dockerfile.server
