apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping-pong-server
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect if not using HTTPS
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ping-pong-server
                port:
                  number: 10000
