apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-server
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
