apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server
spec:
  selector:
    app: ping-pong-server
  ports:
    - name: grpc
      port: 10000  # Replace with the gRPC server port of your Go application
      targetPort: 10000
